name: build and develop

on:
  push:
    branches:
      - main

jobs:
jobs:
  build-and-develop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install-and-unpack
        run: |
          wget "https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.2.0/shiroa-x86_64-unknown-linux-gnu.tar.gz"
          tar -zxvf shiroa-x86_64-unknown-linux-gnu.tar.gz
          cp shiroa-x86_64-unknown-linux-gnu/shiroa shiroa
      - name: Install CNS11643 fonts
        uses: RisingInIris2017/cjk-fonts-action@v1 
      - name: build
        run: ./shiroa build -d ./book
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: Q-wjh213/Q-wjh213.github.io
          publish_dir: ./book
          publish_branch: main  # 推送到目标仓库的 main 分支
          commit_message: "meow~"